/* Generated by S-function Builder */
#ifndef _TMS320F28335_BUS_H_
#define _TMS320F28335_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef _DEFINED_TYPEDEF_FOR_DebugInfL_
#define _DEFINED_TYPEDEF_FOR_DebugInfL_ 
typedef struct {
  real_T IaL;
  real_T IbL;
  real_T IcL;
  real_T IAlphaL;
  real_T IBetaL;
  real_T IdzL;
  real_T IdL;
  real_T SIdL;
  real_T DeltaIdOldL;
  real_T DeltaIdL;
  real_T UUdL;
  real_T IqzL;
  real_T IqL;
  real_T SIqL;
  real_T DeltaIqOldL;
  real_T DeltaIqL;
  real_T UUqL;
  real_T UdSIL;
  real_T UqSIL;
  real_T E_ampL;
  real_T fE_ampL;
  real_T UAlphaSIL;
  real_T UBetaSIL;
  real_T DeltaIAlphaL;
  real_T DeltaIBetaL;
  real_T OldIAlphaL;
  real_T OldIBetaL;
  real_T EAlphaInstL;
  real_T EBetaInstL;
  real_T E_MaxL;
  real_T E_LineL;
  real_T Ez_ampL;
  real_T SEL;
  real_T IqLCurLim;
  real_T IqLMAX;
  real_T fIqLMAX;
  real_T UAlphaL;
  real_T UBetaL;
  real_T UUAL;
  real_T UUBL;
  real_T UUCL;
  real_T ChopReg;
  real_T UUqzL;
  real_T fUmL;
  real_T UmL;
  real_T DeltaIdzL;
  real_T dEL;
  real_T sdEL;
  real_T UkdL;
  real_T UkqL;
  real_T ThetaSlipL;
  real_T fThetaL;
  real_T EbyFreqL;
  real_T LmL16;
  real_T FreqL16;
  real_T AFSpeedzL16;
  real_T DeltaSpeedL;
  real_T SpeedLz1_16;
  real_T DeltaSpeedL1;
  real_T PowerL;
  real_T PowerL16;
  real_T Iaz;
  real_T Ibz;
  real_T Icz;
  real_T IAlphaz;
  real_T Ibetaz;
  real_T ImL;
  real_T iffL;
  real_T IfRMSL;
  real_T AmplL;
  real_T AlphaL;
} DebugInfL;
#endif

/* Read only - ENDS */


#endif
