/* Generated by S-function Builder */
#ifndef _TMS320F28335_BUS_H_
#define _TMS320F28335_BUS_H_
/* Read only - STARTS */
#ifdef MATLAB_MEX_FILE
#include "tmwtypes.h"
#else
#include "rtwtypes.h"
#endif




#ifndef _DEFINED_TYPEDEF_FOR_BusObject_
#define _DEFINED_TYPEDEF_FOR_BusObject_ 
typedef struct {
  real_T IaL;
} BusObject;
#endif

/* Read only - ENDS */


#endif
